[package]
name = "micro_loan_platform"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = "0.9.2"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
soroban-sdk = { version = "0.9.2", features = ["testutils"] }

[lib]
crate-type = ["cdylib"]