[package]
name = "micro_loan_platform"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = "20.0.0"  # Use latest version
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
soroban-sdk = { version = "20.0.0", features = ["testutils"] }

[lib]
crate-type = ["cdylib"]